services:
  - type: web
    name: omniflow-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: ./backend
    healthCheckPath: /

  - type: web           # ← بدل static إلى web
    name: omniflow-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: omniflow-backend
